config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :posts
  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  root to: 'welcome#index'

  # sign up page with form:
  post '/register' => 'users#create', as: :create_user

  # create (post) action for when sign up form is submitted:



  # log in page with form:
  get '/login' => 'sessions#new', as: :login

  # create (post) action for when log in form is submitted:
  post '/login' => 'sessions#create'

  # delete action to log out:
  delete '/logout' => 'sessions#destroy', as: :logout
  
  # OPTIONAL secret page (requires a user to be signed in):
  get 'pages/secret' => 'pages#secret'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates_presence_of :username
	validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def user_is_logged_in
    	if !session[:user_id]
        	return false
    	end
    	return true
	end
	def user_isnt_logged_in
    	if session[:user_id]
        	redirect_to root_path
    	end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    render layout: false
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    render layout: false
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:id, :name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    render layout: false
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    if(!user_is_logged_in) 
      redirect_to login_path
    end
    param = post_params
    param[:user_id] = session[:user_id]
    @post = Post.new(param)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :image, :description, :body, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		render layout: false
	end
	def create
		user = User
			.find_by(username: params[:user][:username])
			.try(:authenticate, params[:user][:password])
	  	if(user)
	  		session[:user_id] = user.id
	  		redirect_to root_path
	  	else
	  		render json: {
	  			status: 401
	  		}
	  	end
	end
	def destroy
		session.delete(:user_id)
    	redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    user = User.new
  end


  def create

  	user = User.find_by(username: user_params[:username])
  	if(user)
  		render html: '<div>Tai khoan da ton tai</div>'.html_safe
  	else
  		@user = User.new(user_params)
  		@user.username.downcase!
  		if(@user.save)
        session[:user_id] = @user.id
    		redirect_to root_path
	    else
	    	render html: '<div>Errors</div>'.html_safe
	    end
  	end
  end

  private

  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@is_logged_in = user_is_logged_in
  	@categories = Category.all.sort{ |a,b| a[:name].length <=> b[:name].length }
  	@posts = Post.all
  	@random_post = @posts.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div style="margin-top: 200px">
	<h1>Editing Category</h1>

	<%= render 'form', category: @category %>

	<%= link_to 'Show', @category %> |
	<%= link_to 'Back', categories_path %>
	
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= button_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @category.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EndGame - Gaming Magazine Template</title>
    <meta charset="UTF-8">
    <meta name="description" content="EndGam Gaming Magazine Template">
    <meta name="keywords" content="endGam,gGaming, magazine, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link href="img/favicon.ico" rel="shortcut icon"/>


    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


  <!-- Stylesheets -->
    <%= stylesheet_link_tag "bootstrap.min" %>
    <%= stylesheet_link_tag "fontawesome" %>
    <%= stylesheet_link_tag "slicknav.min" %>
    <%= stylesheet_link_tag "owl.carousel.min" %>
    <%= stylesheet_link_tag "magnific-popup" %>
    <%= stylesheet_link_tag "animate" %>


  <!-- Main Stylesheets -->
    <%= stylesheet_link_tag "welcome" %>  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag Ckeditor.cdn_url%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v10.0&appId=895700327905265&autoLogAppEvents=1" nonce="pT3tqFUj"></script>
  </head>

  <body>
    <!-- Header section -->

    <header class="header-section">
      <div class="header-warp">
        <div class="header-social d-flex justify-content-end">
          <p>Follow us:</p>
          <a href="#"><i class="fab fa-2x fa-facebook-square"></i></a>
          <a href="#"><i class="fab fa-2x fa-twitter-square"></i></a>
          <a href="#"><i class="fab fa-2x fa-dribbble-square"></i></a>
          <a href="#"><i class="fab fa-2x fa-behance-square"></i></a>
        </div>
        <div class="header-bar-warp d-flex">
          <!-- site logo -->
          <a href="home.html" class="site-logo">
            <%= image_tag("logo.png") %>
          </a>
          <nav class="top-nav-area w-100">
            <div class="user-panel">
              <% if session[:user_id] %>
              Hello 
              <span style="color: #dc00f5"><%= User.find(session[:user_id]).username %></span>,
              <%= link_to 'Logout', logout_path, method: :delete %>
              <% else %>
              <a href="<%= login_path %>">Login</a> / <a href="">Register</a>
              <% end %>
            </div>
            <!-- Menu -->
            <ul class="main-menu primary-menu">
              <li><%= link_to 'Home', root_path%></li>
              <li><a href="games.html">Games</a>
                <ul class="sub-menu">
                  <li><a href="game-single.html">Game Singel</a></li>
                </ul>
              </li>
              <li><a href="review.html">Reviews</a></li>
              <li><a href="blog.html">News</a></li>
              <li><a href="contact.html">Contact</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <%= yield %>
    <section class="newsletter-section">
      <div class="container">
        <h2>Subscribe to our newsletter</h2>
        <form class="newsletter-form">
          <input type="text" placeholder="ENTER YOUR E-MAIL">
          <button class="site-btn">subscribe  <%= image_tag("icons/double-arrow.png", :alt => "") %></button>
        </form>
      </div>
    </section>
    <!-- Newsletter section end -->


    <!-- Footer section -->
    <footer class="footer-section">
      <div class="container">
        <div class="footer-left-pic">
          <%= image_tag("footer-left-pic.png", :alt => "") %>
        </div>
        <div class="footer-right-pic">
          <%= image_tag("footer-right-pic.png", :alt => "") %>
        </div>
        <a href="#" class="footer-logo">
          <%= image_tag("logo.png", :alt => "") %>
        </a>
        <ul class="main-menu footer-menu">
          <li><a href="">Home</a></li>
          <li><a href="">Games</a></li>
          <li><a href="">Reviews</a></li>
          <li><a href="">News</a></li>
          <li><a href="">Contact</a></li>
        </ul>
        <div class="footer-social d-flex justify-content-center">
          <a href="#"><i class="fab fa-pinterest-square"></i></a>
          <a href="#"><i class="fab fa-facebook-square"></i></a>
          <a href="#"><i class="fab fa-twitter-square"></i></a>
          <a href="#"><i class="fab fa-dribbble-square"></i></a>
          <a href="#"><i class="fab fa-behance-square"></i></a>
        </div>
        <div class="copyright"><a href="">Colorlib</a> 2018 @ All rights reserved</div>
      </div>
    </footer>
    <footer>
      
      <!--====== Javascripts & Jquery ======-->
      <%= javascript_include_tag "jquery-3.2.1.min", "data-turbolinks-track" => true  %>
      <%= javascript_include_tag "welcome", "data-turbolinks-track" => true  %>
      <%= javascript_include_tag "jquery.magnific-popup.min", "data-turbolinks-track" => true  %>
      <%= javascript_include_tag "jquery.slicknav.min", "data-turbolinks-track" => true  %>
      <%= javascript_include_tag "bootstrap.min", "data-turbolinks-track" => true  %>
      <%= javascript_include_tag "owl.carousel.min", "data-turbolinks-track" => true  %>
      <%= javascript_include_tag "jquery.sticky-sidebar.min", "data-turbolinks-track" => true  %>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="text-dark">
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.cktext_area :body, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name), class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container" style="margin-top: 200px">
	
	<h1>Editing Post</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Show', @post, class: "btn btn-primary" %>
	<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

</div>

app/views/posts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Posts</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Post by</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.description %></td>
          <td><%= User.find(post.user_id).username %></td>
          <td><%= Category.find(post.category_id).name %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container" style="margin-top: 200px">
	<h1>New Post</h1>

	<%= render 'form', post: @post%>

	<%= link_to 'Back', posts_path %>
		
</div>

app/views/welcome/index.html.erb
<body>

	<!-- Hero section -->
	<section class="hero-section overflow-hidden">
		<div class="hero-slider owl-carousel">
			<div class="hero-item set-bg d-flex align-items-center justify-content-center text-center" data-setbg="<%= image_path("slider-bg-1.jpg") %>">
				<div class="container">
					<h2>Game on!</h2>
					<p>Fusce erat dui, venenatis et erat in, vulputate dignissim lacus. Donec vitae tempus dolor,<br>sit amet elementum lorem. Ut cursus tempor turpis.</p>
					<a href="#" class="site-btn">Read More
						<%= image_tag("icons/double-arrow.png", :alt => "") %>
					</a>
				</div>
			</div>
			<div class="hero-item set-bg d-flex align-items-center justify-content-center text-center" data-setbg="<%= image_path("slider-bg-2.jpg") %>">
				<div class="container">
					<h2>Game on!</h2>
					<p>Fusce erat dui, venenatis et erat in, vulputate dignissim lacus. Donec vitae tempus dolor,<br>sit amet elementum lorem. Ut cursus tempor turpis.</p>
					<a href="#" class="site-btn">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
				</div>
			</div>
		</div>
	</section>
	<!-- Hero section end-->


	<!-- Intro section -->
	<section class="intro-section">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="intro-text-box text-box text-white">
						<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
						<h3>The best online game is out now!</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida....</p>
						<a href="#" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="intro-text-box text-box text-white">
						<div class="top-meta">11.11.18  /  in <a href="">Playstation</a></div>
						<h3>Top 5 best games in november</h3>
						<p>Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum  labore suspendisse ultrices gravida....</p>
						<a href="#" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="intro-text-box text-box text-white">
						<div class="top-meta">11.11.18  /  in <a href="">Reviews</a></div>
						<h3>Get this game at a promo price</h3>
						<p>Sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida ncididunt ut labore ....</p>
						<a href="#" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Intro section end -->


	<!-- Blog section -->
	<section class="blog-section spad">
		<div class="container">
			<div class="row">
				<div class="col-xl-9 col-lg-8 col-md-7">
					<div class="section-title text-white">
						<h2>Latest News</h2>
					</div>
					<ul class="blog-filter">
						<li><a href="#">Racing</a></li>
						<li><a href="#">Shooters</a></li>
						<li><a href="#">Strategy</a></li>
						<li><a href="#">Online</a></li>
					</ul>
					<!-- Blog item -->
					<% @posts.each do |post| %>
						<div class="blog-item">
							<div class="blog-thumb">
								<img src="<%= post.image %>" alt="">
							</div>
							<div class="blog-text text-box text-white">
								<div class="top-meta"><%= post.created_at %>  /  in <a href=""><%= Category.find(post.category_id).name %></a></div>
								<h3><%= post.title %></h3>
								<p><%= post.description %></p>
								<a href="<%= post_path(post) %>" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
							</div>
						</div>
					<% end %>
					<div class="blog-item">
						<div class="blog-thumb">
							<img src="<%= image_path("blog/1.jpg") %>" alt="">
						</div>
						<div class="blog-text text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius-mod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consecte-tur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
						</div>
					</div>
					<!-- Blog item -->
					<div class="blog-item">
						<div class="blog-thumb">
							<img src="<%= image_path("blog/2.jpg") %>" alt="">
						</div>
						<div class="blog-text text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius-mod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consecte-tur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
						</div>
					</div>
					<!-- Blog item -->
					<div class="blog-item">
						<div class="blog-thumb">
							<img src="<%= image_path("blog/3.jpg") %>" alt="">
						</div>
						<div class="blog-text text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius-mod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consecte-tur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
						</div>
					</div>
				</div>
				<div class="col-xl-3 col-lg-4 col-md-5 sidebar">
					<div id="stickySidebar">
						<div class="widget-item">
							<h4 class="widget-title">Trending</h4>
							<div class="trending-widget">
								<div class="tw-item">
									<div class="tw-thumb">
										<%= image_tag("blog-widget/1.jpg", :alt => "") %>
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<%= image_tag("blog-widget/2.jpg", :alt => "") %>
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<%= image_tag("blog-widget/3.jpg", :alt => "") %>
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<%= image_tag("blog-widget/4.jpg", :alt => "") %>
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<div class="categories-widget">
								<h4 class="widget-title">categories</h4>
								<ul>
							    <% @categories.each do |category| %>
							        <li><a href=""><%= category.name %></a></li>
							    <% end %>
								</ul>
							</div>
						</div>
						<div class="widget-item">
						<a href="#" class="add">
							<%= image_tag("add.jpg", :alt => "") %>
						</a>
					</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog section end -->


	<!-- Intro section -->
	<section class="intro-video-section set-bg d-flex align-items-end " data-setbg="<%= image_path("promo-bg.jpg") %>">
		<a href="https://www.youtube.com/watch?v=uFsGy5x_fyQ" class="video-play-btn video-popup"><img src="<%= image_path("icons/solid-right-arrow.png") %>" alt="#"></a>
		<div class="container">
			<div class="video-text">
				<h2>Promo video of the game</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
			</div>
		</div>
	</section>
	<!-- Intro section end -->


	<!-- Featured section -->
	<section class="featured-section">
		<div class="featured-bg set-bg" data-setbg="<%= @random_post.image %>"></div>
		<div class="featured-box">
			<div class="text-box">
				<div class="top-meta">
					<%= @random_post.created_at %>  /  in 
					<a href=""><%= Category.find(@random_post.category_id).name %></a>
				</div>
				<h3><%= @random_post.title %></h3>
				<p><%= @random_post.description %></p>
				<a href="<%= post_path(@random_post) %>" class="read-more">Read More  <%= image_tag("icons/double-arrow.png", :alt => "") %></a>
			</div>
		</div>
	</section>
	<!-- Featured section end-->



	<!-- Newsletter section -->
	
</body>